In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
results = pd.read_csv("testing_results_min.txt", sep=",", names=["model", "n_way_test", "n_shot_test", "n_quert_test", "dist", "n_test_episodes", "accuracy"])

In [26]:
results.columns

Index(['model', 'n_way_test', 'n_shot_test', 'n_quert_test', 'dist',
       'n_test_episodes', 'accuracy'],
      dtype='object')

In [27]:
results["n_way"] = [int(model[model.find("w")+1:model.find("s")]) for model in results["model"]]
results["n_shot"] = [int(model[model.find("s")+1:model.find("q")]) for model in results["model"]]
results["n_query"] = [int(model[model.find("q")+1:model.find("e")]) for model in results["model"]]
results["n_episodes"] = [int(model[model.find("e")+1:model.find("e")+3]) for model in results["model"]]

In [28]:
results

,model,n_way_test,n_shot_test,n_quert_test,dist,n_test_episodes,accuracy,n_way,n_shot,n_query,n_episodes
0,MINw30s1q15e10cos,5,1,15,cosine,60,0.273111,30,1,15,10
1,MINw30s1q15e10cos,5,5,15,cosine,60,0.454667,30,1,15,10
2,MINw30s1q15e10euc,5,1,15,euclidean,60,0.289111,30,1,15,10
3,MINw30s1q15e10euc,5,5,15,euclidean,60,0.386000,30,1,15,10
4,MINw20s1q15e10cos,5,1,15,cosine,60,0.289111,20,1,15,10
5,MINw20s1q15e10cos,5,5,15,cosine,60,0.426889,20,1,15,10
6,MINw5s1q15e10cos,5,1,15,cosine,60,0.264000,5,1,15,10
7,MINw5s1q15e10cos,5,5,15,cosine,60,0.379556,5,1,15,10
8,MINw20s1q15e10euc,5,1,15,euclidean,60,0.317333,20,1,15,10
9,MINw20s1q15e10euc,5,5,15,euclidean,60,0.441333,20,1,15,10
10,MINw5s1q15e10euc,5,1,15,euclidean,60,0.278444,5,1,15,10
11,MINw5s1q15e10euc,5,5,15,euclidean,60,0.393333,5,1,15,10
12,MINw20s5q15e10cos,5,1,15,cosine,60,0.284444,20,5,15,10
13,MINw20s5q15e10cos,5,5,15,cosine,60,0.484222,20,5,15,10
14,MINw5s5q15e10cos,5,1,15,cosine,60,0.314444,5,5,15,10
15,MINw5s5q15e10cos,5,5,15,cosine,60,0.445333,5,5,15,10
16,MINw20s5q15e10euc,5,1,15,euclidean,60,0.255111,20,5,15,10
17,MINw20s5q15e10euc,5,5,15,euclidean,60,0.409333,20,5,15,10
18,MINw5s5q15e10euc,5,1,15,euclidean,60,0.273333,5,5,15,10
19,MINw5s5q15e10euc,5,5,15,euclidean,60,0.403778,5,5,15,10

In [12]:
m1[m1.find("w")+1:m1.find("s")]

'30'

In [33]:
results_omn = pd.read_csv("testing_results_omn.txt", sep=",", names=["model", "n_way_test", "n_shot_test", "n_quert_test", "dist", "n_test_episodes", "accuracy"])

In [34]:
results_omn.columns

Index(['model', 'n_way_test', 'n_shot_test', 'n_quert_test', 'dist',
       'n_test_episodes', 'accuracy'],
      dtype='object')

In [35]:
results_omn["n_way"] = [int(model[model.find("w")+1:model.find("s")]) for model in results["model"]]
results_omn["n_shot"] = [int(model[model.find("s")+1:model.find("q")]) for model in results["model"]]
results_omn["n_query"] = [int(model[model.find("q")+1:model.find("e")]) for model in results["model"]]
results_omn["n_episodes"] = [int(model[model.find("e")+1:model.find("e")+3]) for model in results["model"]]

ValueError: Length of values (20) does not match length of index (8)

In [36]:
results_omn

,model,n_way_test,n_shot_test,n_quert_test,dist,n_test_episodes,accuracy
0,OMNw60s1q5e100cos,5,1,15,cosine,1000,0.953520
1,OMNw60s1q5e100cos,5,5,15,cosine,1000,0.988973
2,OMNw60s5q5e100cos,5,1,15,cosine,1000,0.949320
3,OMNw60s5q5e100cos,5,5,15,cosine,1000,0.988920
4,OMNw60s1q5e100euc,5,1,15,euclidean,1000,0.947360
5,OMNw60s1q5e100euc,5,5,15,euclidean,1000,0.986973
6,OMNw60s5q5e100euc,5,1,15,euclidean,1000,0.947133
7,OMNw60s5q5e100euc,5,5,15,euclidean,1000,0.989280